// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseInventoryManagement.DataAccess;

#nullable disable

namespace WarehouseInventoryManagement.DataAccess.Migrations
{
    [DbContext(typeof(WarehouseInventoryManagementDBContext))]
    [Migration("20230602213302_InitialDesign")]
    partial class InitialDesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WarehouseInventoryManagement.DataAccess.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceStatusId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("WarehouseInventoryManagement.DataAccess.Entities.DeviceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "READY"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ACTIVE"
                        });
                });

            modelBuilder.Entity("WarehouseInventoryManagement.DataAccess.Entities.Device", b =>
                {
                    b.HasOne("WarehouseInventoryManagement.DataAccess.Entities.DeviceStatus", "DeviceStatus")
                        .WithMany()
                        .HasForeignKey("DeviceStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
